extern const GeoLayout metalsign[];
extern Lights1 metalsign_Mat00_lights;
extern Lights1 metalsign_Mat1_lights;
extern u8 metalsign__0_rgba16[];
extern u8 metalsign__1_rgba16[];
extern Vtx metalsign_node_001_mesh_layer_1_vtx_0[21];
extern Gfx metalsign_node_001_mesh_layer_1_tri_0[];
extern Vtx metalsign_node_001_mesh_layer_1_vtx_1[4];
extern Gfx metalsign_node_001_mesh_layer_1_tri_1[];
extern Gfx mat_metalsign_Mat00[];
extern Gfx mat_metalsign_Mat1[];
extern Gfx metalsign_node_001_mesh_layer_1[];
extern Gfx metalsign_material_revert_render_settings[];
