extern const GeoLayout starhole[];
extern Lights1 starhole_mat1_lights;
extern Lights1 starhole_mat0_lights;
extern u8 starhole__1_rgba16[];
extern u8 starhole__0_rgba16[];
extern Vtx starhole_node_mesh_layer_1_vtx_0[42];
extern Gfx starhole_node_mesh_layer_1_tri_0[];
extern Vtx starhole_node_mesh_layer_1_vtx_1[10];
extern Gfx starhole_node_mesh_layer_1_tri_1[];
extern Gfx mat_starhole_mat1[];
extern Gfx mat_starhole_mat0[];
extern Gfx starhole_node_mesh_layer_1[];
extern Gfx starhole_material_revert_render_settings[];
